#include <iostream>
#include <algorithm>
#include <queue>
#include <vector>
#include <map>
#include <stack>
#include <cstring>
#include <string.h>
#include <fstream>
#include <memory>
#include <type_traits>
#include <unordered_map>
#include <list>